#!/bin/bash
set -e

if [ -z "$TMUX" ]; then
  echo "Not in tmux"
  exit 0
fi

if [ -z "$1" ]; then
  REPO=$(gh repo list | awk '{print $1}' | fzf)
  if [ -n "$REPO" ]; then
    FULL_URL="https://github.com/$REPO"
  else
    echo "No repository selected."
    exit 0
  fi
else
  FULL_URL="$1"
fi

REPO_FULL_NAME=$(echo "$FULL_URL" | sed -E 's|https?://github.com/||' | sed 's/\.git$//')
OWNER=$(echo "$REPO_FULL_NAME" | cut -d'/' -f1)
REPO_NAME=$(echo "$REPO_FULL_NAME" | cut -d'/' -f2)
LOCAL_PATH="$HOME/github.com/$OWNER/$REPO_NAME"
SESSION_NAME=$(echo "$REPO_NAME" | tr -cd '[:alnum:]-')

if [ ! -d "$LOCAL_PATH" ]; then
  mkdir -p "$(dirname "$LOCAL_PATH")" || {
    echo "Failed to create dir"
    exit 1
  }
  git clone "$FULL_URL" "$LOCAL_PATH" || {
    echo "Failed to download repo"
    exit 1
  }
fi

if ! tmux has-session -t "$SESSION_NAME" 2> /dev/null; then
  tmux new-session -d -s "$SESSION_NAME" -c "$LOCAL_PATH"
fi

tmux switch-client -t "$SESSION_NAME"
