#!/bin/bash

vf() {
  if [ -z "$TMUX" ]; then
    echo "Not in tmux"
    return
  fi

  local dir
  dir=$(find "$HOME" -maxdepth 4 -type d \( -name .cache -o -name go -o -name node_modules \) -prune -o -type d -print | sed "s|^$HOME/||" | fzf --layout=reverse) || return 0

  nvim "$HOME/$dir" +":cd %:p:h" +"Explore"
}
vf
